import {LocaleSwitcher} from "@/components/locale-switcher";
import type {Metadata} from "next";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params
                                         }: LayoutProps<'/[locale]'>) {
    const {locale} = await params;
    const messages = await getMessages({locale});

    return (
        <html
            lang={locale}
            className="h-full antialiased"
            dir={locale.startsWith('ar') ? 'rtl' : 'ltr'} // Set text direction (RTL for Arabic, LTR for others)
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <LocaleSwitcher/>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
